version: "3.7"
services:
  coturn:
    build: ./coturn
    image: tms-coturn-ubuntu
    container_name: tms-coturn-ubuntu
    network_mode: "host"

  janus:
    build: ./janus
    image: janus-centos:test
    container_name: tms-janus-centos
    network_mode: "host"
    env_file:
      - ./sample.env
    depends_on:
      - coturn

  ue_client:
    build: ./ue_client
    image: tms-janus-ue_client
    container_name: tms-janus-ue_client
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./ue_client/src:/usr/share/nginx/html:ro
    env_file:
      - ./sample.env
