version: "3.7"
services:
  janus:
    build: ./janus
    image: janus-centos:test
    container_name: tms-janus-centos
    ports:
      - "8088:8088"
      - "5002:5002"
      - "5004:5004"

  ue_client:
    build: ./ue_client
    image: tms-janus-ue_client
    container_name: tms-janus-ue_client
    ports:
      - "8080:80"
    volumes:
      - ./ue_client/src:/usr/share/nginx/html:ro
      - ./ue_client/nginx.conf:/etc/nginx/nginx.conf:ro
