version: '3.7'
services:
  coturn:
    build: ./coturn
    image: tms-janus/coturn-ubuntu
    container_name: tms-janus-coturn-ubuntu
    # network_mode: 'host'

  janus:
    build: ./janus
    image: tms-janus/janus-centos
    container_name: tms-janus-centos
    # network_mode: 'host'
    # ports:
    #   - '8088:8088'
    #   - '10000-10099:10000-10099/udp'
    # volumes:
    #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    env_file:
      - ./sample.env
    depends_on:
      - coturn

  ffmpeg:
    build: ./ffmpeg
    image: tms-janus/ffmpeg
    container_name: tms-janus-ffmpeg
    # ports:
    #   - '3000:3000'
    #   - '3001:3001'
    # volumes:
    #   - ./ffmpeg/files:/home/node/app/files
    #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    depends_on:
      - janus

  ue_player:
    build:
      context: ./ue_player
      args:
        vue_app_base_url: player
        vue_app_janus_address: janus
        # vue_app_ffmpeg_api_base: https://localhost:3443/ffmpeg
        # vue_app_ffmpeg_push: https://localhost:3001
    image: tms-janus/ue-player:latest
    container_name: tms-janus-ue_player
    # ports:
    #   - '8080:80'
    #   - '443:443'
    # volumes:
    #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    environment:
      - NGINX_WEB_BASE_URL=/player
    env_file:
      - ./sample.env

  ue_demo:
    build: ./ue_demo
    image: tms-janus/ue_demo
    container_name: tms-janus-ue_demo
    # ports:
    #   - '8081:80'
    #   - '443:443'
    volumes:
      - ./ue_demo/src:/usr/share/nginx/html:ro
      #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    env_file:
      - ./sample.env
