version: "3.7"
services:
  coturn:
    build: ./coturn
    image: tms-coturn-ubuntu
    container_name: tms-coturn-ubuntu
    network_mode: "host"

  janus:
    build: ./janus
    image: janus-centos:test
    container_name: tms-janus-centos
    network_mode: "host"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  ue_client:
    build: ./ue_client
    image: tms-janus-ue_client
    container_name: tms-janus-ue_client
    ports:
      - "8080:80"
    volumes:
      - ./ue_client/src:/usr/share/nginx/html:ro
      - ./ue_client/nginx.conf:/etc/nginx/nginx.conf:ro
